### ISSUE TITLE
vcov.PlackettLuce sometimes fails with an error

### ISSUE THREAD

**Issue by DavidFirth** [hturner/PlackettLuce#42]
This was reported initially as an apparent error in `qvcalc`: https://github.com/DavidFirth/qvcalc/issues/7.  But actually the error occurs in `vcov.PlackettLuce`.

The original error report points to a (large!) reproducible example.  In the "educators.R" script for that example, the call to `qvcalc()` fails where it calls `vcov(p_mle)`.

The error occurs on this line of `vcov.PlackettLuce`, it seems:
```
Browse[3]>  fit <-  as.vector(exp(X %*% as.vector(coefs)))
Error in X %*% as.vector(coefs) : 
  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90
```
The issue appears to be that `coefs` and `X` have incompatible dimensions:
```
Browse[3]> length(coefs)
[1] 23
Browse[3]> dim(X)
[1] 16320875       29
```
So the problem is perhaps with the function `poisson_rankings`?

@hturner if you have time to take a look, that would be great.  Otherwise I can investigate this further --- but I don't want to risk messing up something else here!

**Comment by hturner** [comment]
cc @Derek-Jones

This bug was due to incorrect handling of the case where intermediate tie are orders are not observed (e.g. in the educators example, there were ties of order 2, 3, 4, 6 and 12, but not 5, 7, 8, 9, 10 or 11). Since v0.3.1 this has been handled correctly, with the tie parameters for unobserved tie orders set to zero.

Although the immediate issue is fixed, `PlackettLuce()` will still struggle on the educators example, due to the high tie orders. As we note in `?PlackettLuce`

> As the maximum tie order increases, the number of possible choices for each rank increases rapidly, particularly when the total number of items is high. This means that the model will be slower to fit with higher D. In addition, due to the current implementation of the vcov() method, computation of the standard errors (as by summary()) can take almost as long as the model fit and may even become infeasible due to memory limits. As a rule of thumb, for > 10 items and > 1000 rankings, we recommend PlackettLuce() for ties up to order 4. For higher order ties, a rank-ordered logit model, see ROlogit::rologit() or generalized Mallows Model as in BayesMallows::compute_mallows() may be more suitable, as they do not model tied events explicitly.

This is something we hope to improve in **PlackettLuce**, but for now you probably need to use a different model, or exclude rankings with high tie orders.
